function [  ] = icopatch( F, V )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

patch('Faces',F,'Vertices',V,...
    'VertexNormals',V,...
    'LineWidth',0.5,'FaceLighting','phong',...
    'BackFaceLighting','unlit',...
    'AmbientStrength',0.3,'DiffuseStrength',0.6,...
    'SpecularExponent',10,'SpecularStrength',0.9,...
    'FaceColor','flat','CData',V(:,3),...
    'Parent',gca,'Tag','Icosphere');

end

